### ISSUE TITLE
`test_read_ice_input` fails because test data have been reanmed

### ISSUE THREAD

**Issue by singularitti** [MineralsCloud/qha#67]
## Expected Behavior
[`test_read_ice_input`](https://github.com/MineralsCloud/qha/blob/973ccff4e7ef4fe0c4ddbfddde685fca99a14547/qha/tests/test_read_input.py#L24) runs through without error

## Actual Behavior
[`test_read_ice_input`](https://github.com/MineralsCloud/qha/blob/973ccff4e7ef4fe0c4ddbfddde685fca99a14547/qha/tests/test_read_input.py#L24) runs with error
```python
Error
Traceback (most recent call last):
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/qz/.ghq/github.com/MineralsCloud/qha/qha/tests/test_read_input.py", line 27, in test_read_ice_input
    nm, volumes, static_energies, frequencies, q_weights = read_input(file_path)
  File "/Users/qz/.ghq/github.com/MineralsCloud/qha/qha/basic_io/read_input.py", line 37, in read_input
    text_stream = TextStream(pathlib.Path(inp))
  File "/Users/qz/.virtualenvs/qha-Z2YbyQSM/lib/python3.6/site-packages/text_stream/__init__.py", line 58, in __init__
    "The *inp* argument '{0}' is not a valid file!".format(inp))
FileNotFoundError: The *inp* argument '../../examples/ice VII/input_conf01' is not a valid file!
```

## Reason
`examples/ice VII/input_conf01`, etc., have been renamed to `examples/ice VII/input_01`, etc.

## Specifications

  - Version: `qha` 1.0.16
  - Platform: All
  - Subsystem: All

**Comment by singularitti** [comment]
Fixed by [commit `380a761eb0ee09d651cfd6e861c6f840e4ae298a`](https://github.com/MineralsCloud/qha/commit/380a761eb0ee09d651cfd6e861c6f840e4ae298a).
