### ISSUE TITLE
`test_ho_free_energy` fails because of numerical error

### ISSUE THREAD

**Issue by singularitti** [MineralsCloud/qha#68]
## Expected Behavior
```python
self.assertEqual(ho_free_energy(0, 1000), 0.004556299262079407)
self.assertEqual(ho_free_energy(100, 1000), 0.0045562989049199466)
```
pass through.

## Actual Behavior
```python
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0.004556335252869987 != 0.004556299262079407

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/qz/.ghq/github.com/MineralsCloud/qha/qha/tests/test_single_configuration.py", line 13, in test_ho_free_energy
    self.assertEqual(ho_free_energy(0, 1000), 0.004556299262079407)
```
and
```python
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0.004556334895497172 != 0.0045562989049199466

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/qz/.pyenv/versions/3.6.8/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/qz/.ghq/github.com/MineralsCloud/qha/qha/tests/test_single_configuration.py", line 14, in test_ho_free_energy
    self.assertEqual(ho_free_energy(100, 1000), 0.0045562989049199466)
```

## Steps to Reproduce the Problem

  1. Install `numba` 0.44.0

## Specifications

  - Version: `qha` 1.0.16, `numba` 0.44.0
  - Platform: All
  - Subsystem: All

**Comment by singularitti** [comment]
Fixed in [commit `a75cab0c44c0f33e9da1450e5e3279d655064d4d`](https://github.com/MineralsCloud/qha/commit/a75cab0c44c0f33e9da1450e5e3279d655064d4d).
